sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install 'coverage >= 4.0a5'
  - pip install coveralls
  - python setup.py install
script:
  - coverage run setup.py test
after_success:
  - coverage combine
  - coveralls
