sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - pip install --requirement=requirements-flake8.txt
  - pip install 'coverage >= 4.0a5'
  - pip install 'coveralls >= 1.0a2'
  - LC_ALL=C pip install .
script:
  - make check
  - coverage run setup.py test
after_success:
  - coverage combine
  - coveralls
